name: build
on: [push]
jobs:
    linux-gcc:
        runs-on: ubuntu-latest
        steps:
            - name: install g++-5
              run: sudo apt-get install -y g++-5
            - uses: actions/checkout@v1
              with:
                fetch-depth: 1
            - name: make project
              working-directory: projects
              run: |
                ./genie --gcc=linux-gcc-5 gmake
            - name: build engine
              working-directory: projects/tmp/gcc5
              shell: bash
              run: |
                make
    
